<div class="container mt-5">
    <h1>Cadastro de Pessoal</h1>
    <table class="table table-hover">
        <tr>
            <th>Nome Completo</th>
            <th>Telefone</th>
            <th>CPF</th>
            <th>Data de Nascimento</th>
            <th>CEP</th>
            <th>Logradouro</th>
            <th>Localidade</th>
            <th>Bairro</th>
            <th>UF</th>
            <th>Complemento</th>
        </tr>
        <?php foreach ($this->view->dados as $indice => $pessoa) { ?>
        <tr>
            <td><?php echo $pessoa['nome_completo']; ?></td>
            <td><?php echo $pessoa['telefone']; ?></td>
            <td><?php echo $pessoa['cpf']; ?></td>
            <td><?php echo $pessoa['data_nascimento']; ?></td>
            <td><?php echo $pessoa['cep']; ?></td>
            <td><?php echo $pessoa['logadouro']; ?></td>
            <td><?php echo $pessoa['localidade']; ?></td>
            <td><?php echo $pessoa['bairro']; ?></td>
            <td><?php echo $pessoa['uf']; ?></td>
            <td><?php echo $pessoa['complemento']; ?></td>
        </tr>
        <?php } ?>
    </table>
</div>
